//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string book_desc { get; set; }
        public string book_cover { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> book_category { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
