//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRecord()
        {
            this.PurchaseRecordBooks = new HashSet<PurchaseRecordBook>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_ { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
        public string trx { get; set; }
        public string address_ { get; set; }
        public Nullable<int> confirmed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRecordBook> PurchaseRecordBooks { get; set; }
        public virtual User User { get; set; }
    }
}
