//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string fullname { get; set; }
        public string phone { get; set; }
        public string address_ { get; set; }
        public string image_ { get; set; }
        public Nullable<int> type_ { get; set; }
    }
}
