//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string user_email { get; set; }
        public string user_password { get; set; }
        public Nullable<System.DateTime> user_joindate { get; set; }
        public string user_fullname { get; set; }
        public string user_phone { get; set; }
        public string user_address { get; set; }
        public string user_image { get; set; }
        public Nullable<int> user_type { get; set; }
    }
}
